# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../../notebooks/models/BERT/06_BERT-Training.ipynb.

# %% auto 0
__all__ = ['manual_seed_all']

# %% ../../../../notebooks/models/BERT/06_BERT-Training.ipynb 2
import random
import numpy as np


# Fix seed for experimenting
import torch


def manual_seed_all(
    seed,
):
    torch.manual_seed(seed)

    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)

    np.random.seed(seed)
    random.seed(seed)

    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
