# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../notebooks/utils/01_plot_utils.ipynb.

# %% auto 0
__all__ = ['LivePlot']

# %% ../../../notebooks/utils/01_plot_utils.ipynb 1
from IPython.display import clear_output


class LivePlot:
    def __init__(self, figure_id=0, figsize=(7, 5), title="", xlabel="epochs"):
        self.figure_id = figure_id
        self.figsize = figsize
        self.title = title
        self.xlabel = xlabel

    def plot(self, data_dict):
        from matplotlib import pyplot as plt

        clear_output(wait=True)
        plt.figure(num=self.figure_id, figsize=self.figsize)
        for label, data in data_dict.items():
            plt.plot(data, label=label)
        plt.title(self.title)
        plt.grid(True)
        plt.xlabel(self.xlabel)
        plt.legend(loc="center left")  # the plot evolves to the right
        plt.show()
